// GENERATED by scripts/generate-layouts.js — edit scripts/questions.source.js and
// run `node scripts/generate-layouts.js` instead of changing this file by hand.
//
// Each question is a flow puzzle:
//   chips:   every box on the board. Some are decoys that belong to other flows.
//   links:   the pairs that must be joined (order doesn't matter).
//   layouts: ready-made box positions (centre as a 0–1 fraction of the board);
//            one is picked at random each time the question is shown.
export const QUESTIONS = [
  {
    "id": "q1",
    "title": "ELD compliance flow",
    "chips": [
      {
        "id": "decoy3",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "compliance",
        "label": "ELD Give Compliance"
      },
      {
        "id": "decoy2",
        "label": "Driver Give Product"
      },
      {
        "id": "decoy1",
        "label": "Driver Give POD"
      },
      {
        "id": "decoy4",
        "label": "Driver Give BOL"
      },
      {
        "id": "eld",
        "label": "ELD"
      }
    ],
    "links": [
      [
        "eld",
        "compliance"
      ],
      [
        "compliance",
        "driver"
      ]
    ],
    "layouts": [
      {
        "decoy3": [
          0.35,
          0.15
        ],
        "driver": [
          0.75,
          0.36
        ],
        "compliance": [
          0.33,
          0.84
        ],
        "decoy2": [
          0.81,
          0.65
        ],
        "decoy1": [
          0.28,
          0.43
        ],
        "decoy4": [
          0.77,
          0.91
        ],
        "eld": [
          0.82,
          0.11
        ]
      },
      {
        "decoy3": [
          0.49,
          0.13
        ],
        "driver": [
          0.71,
          0.6
        ],
        "compliance": [
          0.18,
          0.88
        ],
        "decoy2": [
          0.61,
          0.87
        ],
        "decoy1": [
          0.31,
          0.38
        ],
        "decoy4": [
          0.26,
          0.64
        ],
        "eld": [
          0.75,
          0.35
        ]
      },
      {
        "decoy3": [
          0.39,
          0.42
        ],
        "driver": [
          0.31,
          0.86
        ],
        "compliance": [
          0.6,
          0.08
        ],
        "decoy2": [
          0.74,
          0.82
        ],
        "decoy1": [
          0.81,
          0.34
        ],
        "decoy4": [
          0.26,
          0.64
        ],
        "eld": [
          0.79,
          0.6
        ]
      }
    ]
  },
  {
    "id": "q2",
    "title": "Product delivery flow",
    "chips": [
      {
        "id": "decoy2",
        "label": "Shipper Give BOL"
      },
      {
        "id": "receiver",
        "label": "Receiver"
      },
      {
        "id": "shipperProduct",
        "label": "Shipper Give Product"
      },
      {
        "id": "decoy3",
        "label": "Driver Give POD"
      },
      {
        "id": "driverProduct",
        "label": "Driver Give Product"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "decoy4",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "decoy1",
        "label": "Driver Give Signed RC"
      }
    ],
    "links": [
      [
        "shipperProduct",
        "driver"
      ],
      [
        "driver",
        "driverProduct"
      ],
      [
        "driverProduct",
        "receiver"
      ]
    ],
    "layouts": [
      {
        "decoy2": [
          0.19,
          0.37
        ],
        "receiver": [
          0.64,
          0.24
        ],
        "shipperProduct": [
          0.71,
          0.7
        ],
        "decoy3": [
          0.8,
          0.49
        ],
        "driverProduct": [
          0.28,
          0.63
        ],
        "driver": [
          0.24,
          0.09
        ],
        "decoy4": [
          0.29,
          0.84
        ],
        "decoy1": [
          0.82,
          0.92
        ]
      },
      {
        "decoy2": [
          0.3,
          0.7
        ],
        "receiver": [
          0.19,
          0.31
        ],
        "shipperProduct": [
          0.77,
          0.45
        ],
        "decoy3": [
          0.64,
          0.21
        ],
        "driverProduct": [
          0.77,
          0.87
        ],
        "driver": [
          0.22,
          0.91
        ],
        "decoy4": [
          0.8,
          0.66
        ],
        "decoy1": [
          0.23,
          0.09
        ]
      },
      {
        "decoy2": [
          0.66,
          0.78
        ],
        "receiver": [
          0.79,
          0.32
        ],
        "shipperProduct": [
          0.67,
          0.11
        ],
        "decoy3": [
          0.78,
          0.54
        ],
        "driverProduct": [
          0.19,
          0.3
        ],
        "driver": [
          0.25,
          0.84
        ],
        "decoy4": [
          0.38,
          0.56
        ],
        "decoy1": [
          0.19,
          0.09
        ]
      }
    ]
  },
  {
    "id": "q3",
    "title": "Rate confirmation flow",
    "chips": [
      {
        "id": "decoy2",
        "label": "Driver Give POD"
      },
      {
        "id": "brokerRc",
        "label": "Broker Rate Confirmation"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "broker",
        "label": "Broker"
      },
      {
        "id": "decoy3",
        "label": "Dispatcher Give Pickup No"
      },
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "dispatcherRc",
        "label": "Dispatcher Rate Confirmation"
      }
    ],
    "links": [
      [
        "broker",
        "brokerRc"
      ],
      [
        "brokerRc",
        "dispatcher"
      ],
      [
        "dispatcher",
        "dispatcherRc"
      ],
      [
        "dispatcherRc",
        "driver"
      ]
    ],
    "layouts": [
      {
        "decoy2": [
          0.25,
          0.8
        ],
        "brokerRc": [
          0.2,
          0.11
        ],
        "decoy1": [
          0.73,
          0.39
        ],
        "broker": [
          0.74,
          0.68
        ],
        "decoy3": [
          0.29,
          0.37
        ],
        "dispatcher": [
          0.81,
          0.13
        ],
        "driver": [
          0.2,
          0.59
        ],
        "dispatcherRc": [
          0.66,
          0.9
        ]
      },
      {
        "decoy2": [
          0.4,
          0.65
        ],
        "brokerRc": [
          0.82,
          0.37
        ],
        "decoy1": [
          0.36,
          0.34
        ],
        "broker": [
          0.7,
          0.86
        ],
        "decoy3": [
          0.75,
          0.13
        ],
        "dispatcher": [
          0.2,
          0.1
        ],
        "driver": [
          0.22,
          0.91
        ],
        "dispatcherRc": [
          0.81,
          0.62
        ]
      },
      {
        "decoy2": [
          0.72,
          0.33
        ],
        "brokerRc": [
          0.32,
          0.89
        ],
        "decoy1": [
          0.4,
          0.61
        ],
        "broker": [
          0.25,
          0.09
        ],
        "decoy3": [
          0.73,
          0.86
        ],
        "dispatcher": [
          0.69,
          0.09
        ],
        "driver": [
          0.19,
          0.33
        ],
        "dispatcherRc": [
          0.82,
          0.65
        ]
      }
    ]
  },
  {
    "id": "q4",
    "title": "Pickup BOL flow",
    "chips": [
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "shipperBol",
        "label": "Shipper Give BOL"
      },
      {
        "id": "decoy2",
        "label": "Dispatcher Give POD"
      },
      {
        "id": "receiver",
        "label": "Receiver"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "decoy3",
        "label": "Dispatcher Give CD"
      },
      {
        "id": "driverBol",
        "label": "Driver Give BOL"
      }
    ],
    "links": [
      [
        "shipperBol",
        "driver"
      ],
      [
        "driver",
        "driverBol"
      ],
      [
        "driverBol",
        "receiver"
      ],
      [
        "driverBol",
        "dispatcher"
      ]
    ],
    "layouts": [
      {
        "dispatcher": [
          0.4,
          0.16
        ],
        "decoy1": [
          0.71,
          0.38
        ],
        "shipperBol": [
          0.59,
          0.87
        ],
        "decoy2": [
          0.28,
          0.62
        ],
        "receiver": [
          0.75,
          0.62
        ],
        "driver": [
          0.19,
          0.38
        ],
        "decoy3": [
          0.82,
          0.14
        ],
        "driverBol": [
          0.18,
          0.87
        ]
      },
      {
        "dispatcher": [
          0.39,
          0.62
        ],
        "decoy1": [
          0.3,
          0.31
        ],
        "shipperBol": [
          0.71,
          0.11
        ],
        "decoy2": [
          0.77,
          0.9
        ],
        "receiver": [
          0.8,
          0.59
        ],
        "driver": [
          0.34,
          0.92
        ],
        "decoy3": [
          0.83,
          0.32
        ],
        "driverBol": [
          0.28,
          0.1
        ]
      },
      {
        "dispatcher": [
          0.42,
          0.66
        ],
        "decoy1": [
          0.73,
          0.32
        ],
        "shipperBol": [
          0.82,
          0.87
        ],
        "decoy2": [
          0.25,
          0.92
        ],
        "receiver": [
          0.26,
          0.43
        ],
        "driver": [
          0.22,
          0.16
        ],
        "decoy3": [
          0.82,
          0.61
        ],
        "driverBol": [
          0.81,
          0.09
        ]
      }
    ]
  },
  {
    "id": "q5",
    "title": "POD flow: receiver to dispatcher",
    "chips": [
      {
        "id": "decoy3",
        "label": "Dispatcher Give Pickup No"
      },
      {
        "id": "driverPod",
        "label": "Driver Give POD"
      },
      {
        "id": "decoy4",
        "label": "Driver Give Product"
      },
      {
        "id": "receiverPod",
        "label": "Receiver POD"
      },
      {
        "id": "decoy2",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give POD"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      }
    ],
    "links": [
      [
        "receiverPod",
        "driver"
      ],
      [
        "driver",
        "driverPod"
      ],
      [
        "driverPod",
        "dispatcher"
      ]
    ],
    "layouts": [
      {
        "decoy3": [
          0.61,
          0.37
        ],
        "driverPod": [
          0.74,
          0.82
        ],
        "decoy4": [
          0.73,
          0.15
        ],
        "receiverPod": [
          0.27,
          0.78
        ],
        "decoy2": [
          0.77,
          0.58
        ],
        "decoy1": [
          0.2,
          0.3
        ],
        "driver": [
          0.28,
          0.09
        ],
        "dispatcher": [
          0.2,
          0.51
        ]
      },
      {
        "decoy3": [
          0.43,
          0.32
        ],
        "driverPod": [
          0.27,
          0.82
        ],
        "decoy4": [
          0.4,
          0.6
        ],
        "receiverPod": [
          0.8,
          0.89
        ],
        "decoy2": [
          0.63,
          0.1
        ],
        "decoy1": [
          0.8,
          0.57
        ],
        "driver": [
          0.17,
          0.08
        ],
        "dispatcher": [
          0.83,
          0.32
        ]
      },
      {
        "decoy3": [
          0.26,
          0.15
        ],
        "driverPod": [
          0.32,
          0.58
        ],
        "decoy4": [
          0.77,
          0.63
        ],
        "receiverPod": [
          0.36,
          0.36
        ],
        "decoy2": [
          0.7,
          0.08
        ],
        "decoy1": [
          0.32,
          0.88
        ],
        "driver": [
          0.75,
          0.91
        ],
        "dispatcher": [
          0.82,
          0.34
        ]
      }
    ]
  },
  {
    "id": "q6",
    "title": "POD flow: dispatcher to shipper",
    "chips": [
      {
        "id": "decoy2",
        "label": "Dispatcher Give CD"
      },
      {
        "id": "broker",
        "label": "Broker"
      },
      {
        "id": "dispatcherPod",
        "label": "Dispatcher Give POD"
      },
      {
        "id": "decoy4",
        "label": "Shipper Give BOL"
      },
      {
        "id": "decoy3",
        "label": "Broker Give RPM"
      },
      {
        "id": "shipper",
        "label": "Shipper"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "brokerPod",
        "label": "Broker Give POD"
      }
    ],
    "links": [
      [
        "dispatcherPod",
        "broker"
      ],
      [
        "broker",
        "brokerPod"
      ],
      [
        "brokerPod",
        "shipper"
      ]
    ],
    "layouts": [
      {
        "decoy2": [
          0.25,
          0.7
        ],
        "broker": [
          0.71,
          0.91
        ],
        "dispatcherPod": [
          0.68,
          0.27
        ],
        "decoy4": [
          0.25,
          0.3
        ],
        "decoy3": [
          0.74,
          0.69
        ],
        "shipper": [
          0.75,
          0.48
        ],
        "decoy1": [
          0.22,
          0.92
        ],
        "brokerPod": [
          0.27,
          0.08
        ]
      },
      {
        "decoy2": [
          0.4,
          0.35
        ],
        "broker": [
          0.69,
          0.86
        ],
        "dispatcherPod": [
          0.75,
          0.14
        ],
        "decoy4": [
          0.34,
          0.57
        ],
        "decoy3": [
          0.78,
          0.57
        ],
        "shipper": [
          0.26,
          0.08
        ],
        "decoy1": [
          0.26,
          0.9
        ],
        "brokerPod": [
          0.82,
          0.35
        ]
      },
      {
        "decoy2": [
          0.71,
          0.49
        ],
        "broker": [
          0.2,
          0.8
        ],
        "dispatcherPod": [
          0.8,
          0.28
        ],
        "decoy4": [
          0.79,
          0.92
        ],
        "decoy3": [
          0.23,
          0.1
        ],
        "shipper": [
          0.23,
          0.58
        ],
        "decoy1": [
          0.31,
          0.35
        ],
        "brokerPod": [
          0.78,
          0.71
        ]
      }
    ]
  },
  {
    "id": "q7",
    "title": "Signed rate confirmation flow",
    "chips": [
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      },
      {
        "id": "broker",
        "label": "Broker"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "decoy2",
        "label": "Broker Rate Confirmation"
      },
      {
        "id": "dispatcherRc",
        "label": "Dispatcher Rate Confirmation"
      },
      {
        "id": "driverSign",
        "label": "Driver Give Signed RC"
      },
      {
        "id": "decoy3",
        "label": "Driver Give POD"
      }
    ],
    "links": [
      [
        "dispatcher",
        "dispatcherRc"
      ],
      [
        "dispatcherRc",
        "driver"
      ],
      [
        "driver",
        "driverSign"
      ],
      [
        "driverSign",
        "broker"
      ]
    ],
    "layouts": [
      {
        "driver": [
          0.33,
          0.83
        ],
        "dispatcher": [
          0.72,
          0.38
        ],
        "broker": [
          0.79,
          0.61
        ],
        "decoy1": [
          0.23,
          0.32
        ],
        "decoy2": [
          0.28,
          0.55
        ],
        "dispatcherRc": [
          0.21,
          0.1
        ],
        "driverSign": [
          0.71,
          0.08
        ],
        "decoy3": [
          0.79,
          0.87
        ]
      },
      {
        "driver": [
          0.19,
          0.9
        ],
        "dispatcher": [
          0.29,
          0.67
        ],
        "broker": [
          0.27,
          0.39
        ],
        "decoy1": [
          0.58,
          0.13
        ],
        "decoy2": [
          0.82,
          0.87
        ],
        "dispatcherRc": [
          0.82,
          0.42
        ],
        "driverSign": [
          0.78,
          0.64
        ],
        "decoy3": [
          0.18,
          0.16
        ]
      },
      {
        "driver": [
          0.23,
          0.17
        ],
        "dispatcher": [
          0.18,
          0.59
        ],
        "broker": [
          0.76,
          0.91
        ],
        "decoy1": [
          0.72,
          0.32
        ],
        "decoy2": [
          0.6,
          0.62
        ],
        "dispatcherRc": [
          0.77,
          0.1
        ],
        "driverSign": [
          0.18,
          0.8
        ],
        "decoy3": [
          0.3,
          0.38
        ]
      }
    ]
  },
  {
    "id": "q8",
    "title": "Broker and dispatcher information flow",
    "chips": [
      {
        "id": "cd",
        "label": "Dispatcher Give CD"
      },
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      },
      {
        "id": "broker",
        "label": "Broker"
      },
      {
        "id": "info",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "rpm",
        "label": "Broker Give RPM"
      },
      {
        "id": "decoy3",
        "label": "Driver Give POD"
      },
      {
        "id": "decoy2",
        "label": "Broker Give Pickup No"
      },
      {
        "id": "decoy1",
        "label": "Driver Give Signed RC"
      }
    ],
    "links": [
      [
        "rpm",
        "dispatcher"
      ],
      [
        "dispatcher",
        "info"
      ],
      [
        "info",
        "broker"
      ],
      [
        "dispatcher",
        "cd"
      ],
      [
        "cd",
        "broker"
      ]
    ],
    "layouts": [
      {
        "cd": [
          0.27,
          0.17
        ],
        "dispatcher": [
          0.24,
          0.68
        ],
        "broker": [
          0.69,
          0.85
        ],
        "info": [
          0.68,
          0.35
        ],
        "rpm": [
          0.7,
          0.14
        ],
        "decoy3": [
          0.68,
          0.6
        ],
        "decoy2": [
          0.23,
          0.39
        ],
        "decoy1": [
          0.21,
          0.92
        ]
      },
      {
        "cd": [
          0.31,
          0.31
        ],
        "dispatcher": [
          0.79,
          0.63
        ],
        "broker": [
          0.69,
          0.87
        ],
        "info": [
          0.75,
          0.11
        ],
        "rpm": [
          0.25,
          0.89
        ],
        "decoy3": [
          0.21,
          0.65
        ],
        "decoy2": [
          0.78,
          0.35
        ],
        "decoy1": [
          0.24,
          0.09
        ]
      },
      {
        "cd": [
          0.75,
          0.9
        ],
        "dispatcher": [
          0.83,
          0.1
        ],
        "broker": [
          0.23,
          0.35
        ],
        "info": [
          0.34,
          0.86
        ],
        "rpm": [
          0.33,
          0.64
        ],
        "decoy3": [
          0.27,
          0.14
        ],
        "decoy2": [
          0.69,
          0.38
        ],
        "decoy1": [
          0.82,
          0.63
        ]
      }
    ]
  },
  {
    "id": "q9",
    "title": "Pickup number flow",
    "chips": [
      {
        "id": "dispatcher",
        "label": "Dispatcher"
      },
      {
        "id": "decoy1",
        "label": "Dispatcher Give Driver Info"
      },
      {
        "id": "brokerPn",
        "label": "Broker Give Pickup No"
      },
      {
        "id": "decoy2",
        "label": "Driver Give BOL"
      },
      {
        "id": "dispatcherPn",
        "label": "Dispatcher Give Pickup No"
      },
      {
        "id": "driver",
        "label": "Driver"
      },
      {
        "id": "broker",
        "label": "Broker"
      },
      {
        "id": "shipperPn",
        "label": "Shipper Give Pickup No"
      }
    ],
    "links": [
      [
        "shipperPn",
        "broker"
      ],
      [
        "broker",
        "brokerPn"
      ],
      [
        "brokerPn",
        "dispatcher"
      ],
      [
        "dispatcher",
        "dispatcherPn"
      ],
      [
        "dispatcherPn",
        "driver"
      ]
    ],
    "layouts": [
      {
        "dispatcher": [
          0.82,
          0.59
        ],
        "decoy1": [
          0.18,
          0.4
        ],
        "brokerPn": [
          0.24,
          0.89
        ],
        "decoy2": [
          0.21,
          0.66
        ],
        "dispatcherPn": [
          0.68,
          0.11
        ],
        "driver": [
          0.64,
          0.86
        ],
        "broker": [
          0.2,
          0.17
        ],
        "shipperPn": [
          0.71,
          0.34
        ]
      },
      {
        "dispatcher": [
          0.17,
          0.83
        ],
        "decoy1": [
          0.26,
          0.4
        ],
        "brokerPn": [
          0.77,
          0.8
        ],
        "decoy2": [
          0.67,
          0.34
        ],
        "dispatcherPn": [
          0.36,
          0.1
        ],
        "driver": [
          0.81,
          0.57
        ],
        "broker": [
          0.25,
          0.62
        ],
        "shipperPn": [
          0.76,
          0.13
        ]
      },
      {
        "dispatcher": [
          0.59,
          0.1
        ],
        "decoy1": [
          0.25,
          0.66
        ],
        "brokerPn": [
          0.77,
          0.56
        ],
        "decoy2": [
          0.32,
          0.43
        ],
        "dispatcherPn": [
          0.2,
          0.89
        ],
        "driver": [
          0.75,
          0.8
        ],
        "broker": [
          0.19,
          0.21
        ],
        "shipperPn": [
          0.8,
          0.35
        ]
      }
    ]
  }
];
